collision_monitor:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: cmd_vel_smoothed
    cmd_vel_out_topic: cmd_vel
    transform_tolerance: 2.0 # potential
    source_timeout: 5.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    # Polygons represent zone around the robot for "stop" and "slowdown" action types,
    # and robot footprint for "approach" action type.
    # Footprint could be "polygon" type with dynamically set footprint from footprint_topic
    # or "circle" type with static footprint set by radius. "footprint_topic" parameter
    # to be ignored in circular case.
    polygons: ["PolygonStop", "PolygonSlow"]
    PolygonStop:
      type: "polygon"
      points: [0.768, 0.47, 0.768, -0.47, -0.768, -0.47, -0.768, 0.47]
      action_type: "stop"
      max_points: 3
      visualize: True
      polygon_pub_topic: polygon_stop
      enabled: True
    PolygonSlow:
      type: "polygon"
      points: [1.068, 0.67, 1.068, -0.67, -1.068, -0.67, -1.068, 0.67]
      action_type: "slowdown"
      max_points: 3
      slowdown_ratio: 0.3
      visualize: True
      polygon_pub_topic: polygon_slowdown
      enabled: True
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: local_costmap/published_footprint
      time_before_collision: 2.0
      simulation_time_step: 0.1
      max_points: 5
      visualize: False
      enabled: False
    observation_sources: ["scan", "left_rear", "right_rear"]
    scan:
      type: "scan"
      topic: scan
      enabled: True
    left_rear:
      type: "range"
      topic: left_rear
      enabled: True
    right_rear:
      type: "range"
      topic: right_rear
      enabled: True
    pointcloud:
      type: "pointcloud"
      topic: intel_realsense_r200_depth/points
      min_height: 0.1
      max_height: 0.5
      enabled: True
