# Copyright 2025 WheelHub Intelligent
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: -1.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 100
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 0.25
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan
    map_topic: map
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    default_nav_through_poses_bt_xml: "/home/nvidia/ros2_ws/src/whi_nav2_bringup/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml"
    default_nav_to_pose_bt_xml: "/home/nvidia/ros2_ws/src/whi_nav2_bringup/behavior_trees/nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid.xml"
    # default_nav_to_pose_bt_xml: "/home/nvidia/ros2_ws/src/whi_nav2_bringup/behavior_trees/navigate_on_route_graph_w_recovery.xml"
    # default_nav_to_pose_bt_xml: "/home/nvidia/ros2_ws/src/whi_nav2_bringup/behavior_trees/navigate_w_replanning_and_recovery_registration.xml"
    # default_nav_to_pose_bt_xml: "/home/nvidia/ros2_ws/src/whi_nav2_bringup/behavior_trees/navigate_plain_with_spin2path.xml"
    bt_loop_duration: 10
    default_server_timeout: 20
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node
    - nav2_path_expiring_timer_condition
    - nav2_globally_updated_goal_condition_bt_node
    - nav2_is_path_valid_condition_bt_node
    - nav2_smooth_path_action_bt_node
    - nav2_compute_route_bt_node
    - nav2_get_pose_from_path_action_bt_node
    - nav2_get_current_pose_action_bt_node
    - nav2_concatenate_paths_action_bt_node
    - nav2_are_poses_near_condition_bt_node
    - whi_nav2_pose_registration_action_bt_node
    - whi_nav2_spin_to_path_action_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 15.0
    # enable_stamped_cmd_vel: true # does not work on foxy
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 2.0 #0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2
      movement_time_allowance: 10.0
    # Goal checker parameters
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    FollowPath:
      # Regulated Pure Pursuit
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      use_velocity_scaled_lookahead_dist: false
      lookahead_dist: 2.0     # effective when use_velocity_scaled_lookahead_dist is false
      min_lookahead_dist: 0.3 # effective when use_velocity_scaled_lookahead_dist is true
      max_lookahead_dist: 1.5 # effective when use_velocity_scaled_lookahead_dist is true
      lookahead_time: 1.5     # effective when use_velocity_scaled_lookahead_dist is true
      use_rotate_to_heading: true
      rotate_to_heading_angular_vel: 0.2  # the angular velocity to use while the use_rotate_to_heading is true
      max_angular_accel: 0.5              # the max angular acceleration to use while the use_rotate_to_heading is true
      rotate_to_heading_min_angle: 0.5236 # The difference in the path orientation and the starting robot orientation to trigger a rotate in place while the use_rotate_to_heading is true
      allow_reversing: false # both use_rotate_to_heading and allow_reversing cannot be set to true at the same time
      transform_tolerance: 0.2
      min_approach_linear_velocity: 0.1
      approach_velocity_scaling_dist: 0.6
      use_collision_detection: true
      max_allowed_time_to_collision: 1.0 # effective when use_collision_detection is true
      use_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 0.9  # effective when use_regulated_linear_velocity_scaling is true
      regulated_linear_scaling_min_speed: 0.25  # effective when use_regulated_linear_velocity_scaling is true
      use_fixed_curvature_lookahead: false
      curvature_lookahead_dist: 0.25
      use_cost_regulated_linear_velocity_scaling: false
      cost_scaling_dist: 0.3 # effective when use_cost_regulated_linear_velocity_scaling is true
      cost_scaling_gain: 1.0 # effective when use_cost_regulated_linear_velocity_scaling is true
      max_robot_pose_search_dist: 8.0
      min_distance_to_obstacle: 0.5
      stateful: true

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

whi_pose_registration_server:
  ros__parameters:
    use_stamped_vel: false
    controller_plugins: ["ChargerRegistration"]
    ChargerRegistration:
      plugin: "whi_pose_registration_clients::ChargerPlanner"

whi_pose_registration_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

whi_nav2_bt_actions_server:
  ros__parameters:
    use_stamped_vel: false
    cycle_frequency: 10.0
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.2
    local_costmap_topic: local_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    action_plugins: ["spin_to_path"]
    spin_to_path:
      plugin: whi_nav2_bt_actions_server/SpinToPath
      simulate_ahead_time: 2.0
      min_rotational_vel: 0.1
      max_rotational_vel: 0.3
      rotational_acc_lim: 1.57
      check_collision: false

whi_nav2_bt_actions_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      transform_tolerance: 0.8
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 8
      height: 8
      resolution: 0.05
      # robot_radius: 0.22
      footprint: "[[0.518, 0.42], [0.518, -0.42], [-0.518, -0.42], [-0.518, 0.42]]"
      plugins: ["obstacle_layer", "inflation_layer", "voxel_layer"]
      filters: ["keepout_filter", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          obstacle_min_range: 0.0
          obstacle_max_range: 2.5
          raytrace_min_range: 0.0
          raytrace_max_range: 3.0
          clearing: True
          marking: True
          observation_persistence: 0.0
          data_type: "LaserScan"
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: False
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 16
        min_obstacle_height: 0.12
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: pointcloud
        pointcloud:
          topic: /rslidar_points
          min_obstacle_height: 0.12
          max_obstacle_height: 2.0
          obstacle_min_range: 0.0
          obstacle_max_range: 2.5
          raytrace_min_range: 0.0
          raytrace_max_range: 3.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
      static_layer:
        map_subscribe_transient_local: True
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: KEEPOUT_ZONE_ENABLED
        filter_info_topic: /keepout_costmap_filter_info
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 1.0
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      transform_tolerance: 0.8
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      # robot_radius: 0.22
      footprint: "[[0.518, 0.42], [0.518, -0.42], [-0.518, -0.42], [-0.518, 0.42]]"
      resolution: 0.1
      plugins: ["static_layer", "obstacle_layer", "inflation_layer", "voxel_layer"]
      filters: ["keepout_filter", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          obstacle_min_range: 0.0
          obstacle_max_range: 3.0
          raytrace_min_range: 0.0
          raytrace_max_range: 3.0
          clearing: True
          marking: True
          observation_persistence: 2.0
          data_type: "LaserScan"
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: False
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 16
        min_obstacle_height: 0.1
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: pointcloud
        pointcloud:
          topic: /rslidar_points
          min_obstacle_height: 0.1
          max_obstacle_height: 2.0
          obstacle_min_range: 0.0
          obstacle_max_range: 3.0
          raytrace_min_range: 0.0
          raytrace_max_range: 3.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: KEEPOUT_ZONE_ENABLED
        filter_info_topic: /keepout_costmap_filter_info
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 2.0
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

keepout_filter_mask_server:
  ros__parameters:
    topic_name: /keepout_filter_mask
    # yaml_filename: ""

keepout_costmap_filter_info_server:
  ros__parameters:
    type: 0
    filter_info_topic: /keepout_costmap_filter_info
    mask_topic: /keepout_filter_mask
    base: 0.0
    multiplier: 1.0

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: /home/nvidia/ros2_ws/field_test_hall.yaml

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 10.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 15.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: false

      # plugin: "nav2_smac_planner/SmacPlanner2D"
      # tolerance: 0.125                      # tolerance for planning if unable to reach exact pose, in meters
      # downsample_costmap: false             # whether or not to downsample the map
      # downsampling_factor: 1                # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      # allow_unknown: false                   # allow traveling in unknown space
      # max_iterations: 1000000               # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      # max_on_approach_iterations: 1000      # maximum number of iterations to attempt to reach goal once in tolerance
      # max_planning_time: 2.0                # max time in s for planner to plan, smooth
      # cost_travel_multiplier: 2.0           # Cost multiplier to apply to search to steer away from high cost areas. Larger values will place in the center of aisles more exactly (if non-`FREE` cost potential field exists) but take slightly longer to compute. To optimize for speed, a value of 1.0 is reasonable. A reasonable tradeoff value is 2.0. A value of 0.0 effective disables steering away from obstacles and acts like a naive binary search A*.
      # use_final_approach_orientation: false # Whether to set the final path pose at the goal's orientation to the requested orientation (false) or in line with the approach angle so the robot doesn't rotate to heading (true)
      # smoother:
      #   max_iterations: 1000
      #   w_smooth: 0.3
      #   w_data: 0.2
      #   tolerance: 1.0e-10
      #   do_refinement: true

      # plugin: "nav2_theta_star_planner/ThetaStarPlanner"
      # how_many_corners: 4
      # w_euc_cost: 1.0
      # w_traversal_cost: 2.0
      # allow_unknown: false

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    wait:
      plugin: "nav2_behaviors/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.5
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.8
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother", "route_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      refinement_num: 2
      # True for Hybrid A* or State Lattice to not smooth over directional changes
      enforce_path_inversion: True
      do_refinement: True
    route_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      refinement_num: 5
      # False for Route Server or others where smoothing out sharp corners is OK
      enforce_path_inversion: False
      do_refinement: True
